export const INITIATE = "INITIATE";
export const INITIATE_SUCCESS = "INITIATE_SUCCESS";
export const INITIATE_FAIL = "INITIATE_FAIL";

export const INFORM_INITIATE = "INFORM_INITIATE";
export const INFORM_INITIATE_SUCCESS = "INFORM_INITIATE_SUCCESS";
export const INFORM_INITIATE_FAIL = "INFORM_INITIATE_FAIL";

export const WAIT_FOR_PARTICIPATE = "WAIT_FOR_PARTICIPATE";
export const WAIT_FOR_PARTICIPATE_SUCCESS = "WAIT_FOR_PARTICIPATE_SUCCESS";
export const WAIT_FOR_PARTICIPATE_FAIL = "WAIT_FOR_PARTICIPATE_FAIL";

export const BREDEEM = "BREDEEM";
export const BREDEEM_SUCCESS = "BREDEEM_SUCCESS";
export const BREDEEM_FAIL = "BREDEEM_FAIL";

export const INFORM_REDEEMED = "INFORM_REDEEMED";
export const INFORM_REDEEMED_SUCCESS = "INFORM_REDEEMED_SUCCESS";
export const INFORM_REDEEMED_FAIL = "INFORM_REDEEMED_FAIL";

export const BDONE = "BDONE";
